version: '3.1'

services:
  tomcat:
    image: tomcat:latest
    ports:
      - 8080
    networks:
            vpcbr:
                ipv4_address: 172.23.0.2
    environment:
      JMX_PORT: 7199
      CATALINA_OPTS: "-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Djava.rmi.server.hostname=172.23.0.2"


networks:
    vpcbr:
        driver: bridge
        ipam:
          config:
            - subnet: 172.23.0.0/16
