---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "7077"
    port: 7077
    targetPort: 7077
  selector:
    io.kompose.service: spark-master
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spark-master
    spec:
      containers:
      - args:
        - bin/spark-class
        - org.apache.spark.deploy.master.Master
        - -h
        - master
        env:
        - name: MASTER
          value: spark://master:7077
        - name: SPARK_PUBLIC_DNS
          value: localhost
        image: gettyimages/spark
        name: spark-master
        ports:
        - containerPort: 8080
        - containerPort: 7077
        resources: {}
      hostname: spark-master
      restartPolicy: Always
status: {}
