version: "3.1"

services:
  jboss:
    image: jboss/wildfly
    container_name: jboss
    ports:
      - 9990:9990
    environment:
      JMX_PORT: 7199
      JAVA_TOOL_OPTIONS: "-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Djava.rmi.server.hostname=172.22.0.2"

