version: '3.1'
services:
  weblogic:
    image: ismaleiva90/weblogic12
    container_name: weblogic
    restart: always
    ports:
      - 7001:7001
    networks:
            vpcbr:
                ipv4_address: 172.14.0.2
    environment:
      JMX_PORT: 7199
      JAVA_OPTIONS: "-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Djava.rmi.server.hostname=172.14.0.2"


networks:
    vpcbr:
        driver: bridge
        ipam:
          config:
            - subnet: 172.14.0.0/16
