version: '2'
services:
  my-kafka:
    image: spotify/kafka 
    hostname: my-kafka
    restart: unless-stopped
    ports:
      - "9092:9092" # Kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: my-kafka
      KAFKA_ADVERTISED_PORT: 9092
      JMX_PORT: 5199

